[package]
name = "tinyrender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.3"
image = "0.24.1"
obj-rs = "0.7.0"
rand = "0.8.5"
structopt = "0.3.26"
tap = "1.0.1"

[features]
